# Generated by Django 6.0.3 on 2026-03-13 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('url', 'URL'), ('code', 'Code Snippet'), ('file', 'File Upload')], max_length=10)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('target_code', models.TextField(blank=True, null=True)),
                ('target_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField()),
                ('risk_score', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('raw_ai_response', models.TextField(blank=True, null=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=10)),
                ('vuln_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('proof_of_concept', models.TextField(blank=True, null=True)),
                ('remediation', models.TextField()),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cwe_id', models.CharField(blank=True, max_length=20, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.scan')),
            ],
            options={
                'ordering': [models.Case(models.When(severity='critical', then=0), models.When(severity='high', then=1), models.When(severity='medium', then=2), models.When(severity='low', then=3), models.When(severity='info', then=4), default=5)],
            },
        ),
    ]
